void main() {
  
  Set <String> name = {'Nurlan', 'Nadira', 'Saliha', 'Hanifa'};
  
  
  name.add('Beautiful_Family' '!');
  print (name);
  
  
}
     
  ////////////////////////////////////////////////////////////////////

void main() {
  
  Set <String> name = {'Nurlan', 'Nadira', 'Saliha', 'Hanifa'};
  
  List <dynamic> age = [29,27,5,3];
  
  Map < int, dynamic > nameAge = {
   
  1: 'Nurlan',
  
  2: 'Nadira',
   
  3: 'Saliha',
  
  4: 'Hanifa',
    
  5: [29,27,5,3],  
 
  };
   

  age.add('vozrast_Nurlan_Nadira_Saliha_Hanifa');
  print (age);
  
  
}
         
//   ////////////////////////////////////


void main() {
  
  Set <String> name = {'Nurlan', 'Nadira', 'Saliha', 'Hanifa'};
  
  List <dynamic> age = [29,27,5,3];
  
  Map < int, dynamic > nameAge = {
   
  1: 'Nurlan',
  
  2: 'Nadira',
   
  3: 'Saliha',
  
  4: 'Hanifa',
    
  5: [29,27,5,3],  
 
  };
   

  print (nameAge [1]); print (age[0]);
  print (nameAge [2]); print (age[1]);
  print (nameAge [3]); print (age[2]);
  print (nameAge [4]); print (age[3]);
  
  
  
}
         
  ////////////////////////////////////////
